baseURL = 'https://vicentube.com/'
languageCode = 'es-ES'
defaultContentLanguage = 'es'
title = 'Vicente Úbeda'
theme = 'stack'

[Params]
favicon = 'favicon.ico'

[Params.Sidebar]
avatar.src = 'img/avatar.jpg'